// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using To_Do_Lists.Data;

namespace To_Do_Lists.Migrations
{
    [DbContext(typeof(ListDbContext))]
    partial class ListDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0-rc.1.20451.13");

            modelBuilder.Entity("To_Do_Lists.Data.Entities.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("ListOfItemsId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ItemId");

                    b.HasIndex("ListOfItemsId");

                    b.ToTable("ItemsTable");
                });

            modelBuilder.Entity("To_Do_Lists.Data.Entities.ListOfItems", b =>
                {
                    b.Property<int>("ListOfItemsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("ListTitle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ListOfItemsId");

                    b.ToTable("ListOfItemsTable");
                });

            modelBuilder.Entity("To_Do_Lists.Data.Entities.Item", b =>
                {
                    b.HasOne("To_Do_Lists.Data.Entities.ListOfItems", "ListOfItems")
                        .WithMany("ToDoList")
                        .HasForeignKey("ListOfItemsId");

                    b.Navigation("ListOfItems");
                });

            modelBuilder.Entity("To_Do_Lists.Data.Entities.ListOfItems", b =>
                {
                    b.Navigation("ToDoList");
                });
#pragma warning restore 612, 618
        }
    }
}
